### ISSUE TITLE
Update "Meet the team" page to include 2023 subcom

### ISSUE THREAD

**Issue by scorpiontornado** [coopsoc/website#20]
- [x] Add 2023 subcom
- [x] Add 2023 first year reps + pics
- [x] Make title, url, header link, and page header consistent (currently "Our Team | UNSW Co-op Society", "https://coopsoc.com.au/team", "The Team", and "MEET THE TEAM", respectively
- [x] Address team.jsx line 40: 'TODO: have this be a subpage of "About"'
- [x] #24 
- [x] Vertically centre left-hand column of subcom section of /team in each row/portfolio (probably involves centring Subcom.jsx `<div className="col-sm-8">` within the parent "row" div)

**Comment by scorpiontornado** [comment]
Also, get pictures for 2023 first year representatives

**Comment by theawesomew** [comment]
If anyone would like to make a pull request for this issue - please feel free. It can be addressed pretty quickly if you'd like to.

**Comment by scorpiontornado** [comment]
Might do it tmr, do you know where pics for the 1st year reps come from? Do I just dm them? @theawesomew

**Comment by scorpiontornado** [comment]
Making naming consistent depending on space available - "team", "the team", and "meet the team" (removing "our team").

**Comment by theawesomew** [comment]
Aks specifically asked me to remove sub-pages because it makes the UI more cluttered and less accessible (you have to search through the user interface for things rather than them being immediately obvious). So, we'll stick to the 'no sub menus' gig because we're never going to have so many pages that we can't just do that :)

**Comment by scorpiontornado** [comment]
@theawesomew how's the vertical centring of the subcom portfolio names/icons going?

**Comment by scorpiontornado** [comment]
Would probably be easy once we're using Reactstrap properly

**Comment by scorpiontornado** [comment]
Was really easy to centre them actually, just had to move `d-flex align-items-center` from the subcom list `col` to the parent `row` (https://stackoverflow.com/a/42252877)
