### ISSUE TITLE
Fix exec descriptions not visible

### ISSUE THREAD

**Issue by scorpiontornado** [coopsoc/website#24]
Descriptions are visible in TeamsData.js and rendered in HTML at coopsoc.com.au/team. However, they appear to be rendered behind each person's image, and are thus not visible.
- [ ] Fix ExecCard.jsx so the descriptions are actually show - could be done with a toggle dropdown, a popup, text overlayed onto the image when clicked etc
- [ ] Add descriptions for 2023 execs, directors, and first year reps

**Comment by theawesomew** [comment]
You don't need to do anything apart form uncomment the description in the ExecCard.js - the show/hide toggling is handled elsewhere already

**Comment by scorpiontornado** [comment]
Could be done later, but honestly a bit of a waste of time right now.

If not done, should probably remove the blue quarter-circles in the corner of the exec images on https://coopsoc.com.au/team - they imply the images are clickable.

**Comment by lhvy** [comment]
In my opinion, we don't need distinct descriptions for each member of the team, and we can just remove the data field, as well as the quarter-circles.

**Comment by scorpiontornado** [comment]
Yeah I'm fine with that, the circles were a neat piece of code though rip

**Comment by scorpiontornado** [comment]
Maybe we could use it for borders?

**Comment by lhvy** [comment]
Nevermind, fixed it already.
