### ISSUE TITLE
Sort out package-lock.json and yarn.lock conflict

### ISSUE THREAD

**Issue by lhvy** [coopsoc/website#27]
Currently the codebase has both `package-lock.json` and `yarn.lock`, and running `yarn install` gives the following error:

```
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
```

I believe, we should decide if we are using Yarn or not, and remove the other file.

**Comment by theawesomew** [comment]
Huh - that's probably my fault. I often use `npm install` rather than `yarn install` - just deleted the package-lock.json and add it to the .gitignore  in case I fuck that up again.

**Comment by lhvy** [comment]
Sounds good! I'll let this issue close with linked PR.
