### ISSUE TITLE
Add 2024 coop facebook link

### ISSUE THREAD

**Issue by scorpiontornado** [coopsoc/website#55]
Perhaps add to header? Just be wary of people spam-requesting to join. Ask Sam for link if needed.

**Comment by KKSurendran06** [comment]
Could you elaborate the issue, I see the link https://www.facebook.com/coopsoc.unsw/ is already present in the header

**Comment by scorpiontornado** [comment]
Don't worry, I'll handle this one. There's an invite link to a private facebook group, but we're currently discussing whether or not it's a good idea to put it on the website

**Comment by KKSurendran06** [comment]
alright

**Comment by lhvy** [comment]
Resolved by #59
